### ISSUE TITLE
EmailWidget does not appear appear in the npm repo

### ISSUE THREAD

**Issue by gary-menzel** [cybertec-postgresql/rjsf-material-ui#100]
@zepatrik (or @agustin107 )

I note the PR merged about 7 days ago that added the `EmailWidget` and can see the change in the source code (although `npm` says the last publish was 8 days ago).

However, the 0.3.8 build from `npm` does not appear to have that widget in the `dist` build.  Did this PR ever get pushed to `npm` ?

I have removed my old `rjsf-material-ui` and added it again with yarn, but still no luck.

When I use a `format` of `email` or a `ui:widget` of `email` I just get the default `input` tag with `type="email"` on it (and not the MUI styled widget).

Any suggestions ?

**Comment by agustin107** [comment]
Now it's deployed. 

https://github.com/cybertec-postgresql/rjsf-material-ui/releases/tag/v0.3.9

**Comment by gary-menzel** [comment]
@agustin107 Thanks for the deployment, however, the `EmailWidget` still appears to be missing for some reason.

I fully removed and re-added `rjsf-material-ui` (with `yarn`) and the version has updated to `0.3.9`. When I console log the `Widgets`  (and when I check the source code - see below).  The `EmailWidget` is still missing.

Here is a quick dump from the source code build showing the Widgets object with the `EmailWidget` still not loading (even though it is the in the repo)....

```javascript
var Widgets = {
  CheckboxWidget: CheckboxWidget,
  CheckboxesWidget: CheckboxesWidget,
  PasswordWidget: PasswordWidget,
  RadioWidget: RadioWidget,
  RangeWidget: RangeWidget,
  SelectWidget: SelectWidget,
  TextareaWidget: TextareaWidget,
  TextWidget: TextWidget,
  UpDownWidget: UpDownWidget
};
```
Compare to the following from the repo:
```
export default {
  CheckboxWidget,
  CheckboxesWidget,
  PasswordWidget,
  RadioWidget,
  RangeWidget,
  SelectWidget,
  TextareaWidget,
  TextWidget,
  UpDownWidget,
  EmailWidget,
};
```

**Comment by cosmin-harangus** [comment]
Any update on this issue? I am having the same issue as described by @gary-menzel when using the latest version of the package. The package bundle seems to not contain the latest version of the codebase.

Can you let me know how to make this work?
