### ISSUE TITLE
Update add button title

### ISSUE THREAD

**Issue by khoa-ng** [cybertec-postgresql/rjsf-material-ui#53]
Hi. Thanks for your supporting me.

I want to update "ADD ITEM" to string I'd love.

do you have any option?

**Comment by agustin107** [comment]
Hey! Thanks for creating an issue.

Now you can do that adding this option on `uiSchema`:

```javascript
{
  "ui:options": {
    "addButtonLabel": "Custom add label"
  }
}

```
